Error alert box style and content changes
ongov/ckanext-validation pull request #3
Opened 2024-04-23 16:12 UTC by KatiRG

## What this PR accomplishes
Changes the style of the error alert box on Step 1 of the new workflow to be consistent with the DS, and customizes the message content

## What needs review
Upload a file that contains invalid headers (e.g. duplicate headers or header names > 63 characters) and confirm that:
- alert box styling is consistent with DS
- alert box content shows a bullet list with one item and the content is: `There is a problem with your data source. Please review the validation report to resolve the issues and try uploading again.`
- the hyperlinked "validation report" opens the validation report modal, as before

Also check that the entire workflow works as expected once a fixed file has been uploaded.

2024-04-25 20:02 UTC, aleeexgreeen requested changes

2024-04-25 20:02 UTC, aleeexgreeen commented on ckanext/validation/templates/scheming/snippets/errors.html
We should revert all changes to this file and add your changes to `{% block errors_list %}` to `ckanext/ontario_theme/templates/internal/scheming/snippets/errors.html` (You'll have to add `snippets/errors.html`). We'll want our error messaging to be consistent within our forms and these changes are not specific to this extension.

2024-04-26 18:21 UTC, KatiRG commented on ckanext/validation/templates/scheming/snippets/errors.html
done!

2024-04-26 18:21 UTC, aleeexgreeen approved these changes

2024-04-26 20:25 UTC, merged